name = "typed_headers"
version = "1.1.0"

description = "Types for HTTP headers"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "LilyRose2798", repo = "typed_headers" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
